version = 0.1
[default.deploy.parameters]
stack_name = "cloudx-UploadsNotificationLambdaFunc"
resolve_s3 = true
s3_prefix = "cloudx-UploadsNotificationLambdaFunc"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
